version: '3.8'

services:
  mega-api:
    build:
      context: .
      dockerfile: mega.Api/Dockerfile
    image: mega-api
    container_name: mega-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your-password
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${HOME}/.aspnet/https:/https/
    restart: unless-stopped
